### ISSUE TITLE
 Presense.js ||  Presence.js 

### ISSUE THREAD

**Issue by dylanjamesdev** [Craftzman7/hypercord#1]
Presense or Presence ;-;

**Comment by dylanjamesdev** [comment]
ignore this Im fucking stupid it looked wrong xD

**Comment by dylanjamesdev** [comment]
WAIt

**Comment by dylanjamesdev** [comment]
I WAS RIGHt

**Comment by Craftzman7** [comment]
I see the issue fixing right now

**Comment by Craftzman7** [comment]
Wait I don't see it lmfao

**Comment by dylanjamesdev** [comment]
RIGHT LMFAOOOO SAME

PresenCe vs presenSe

**Comment by Craftzman7** [comment]
Fixed

**Comment by Craftzman7** [comment]
Lemme know if I messed it up

**Comment by Craftzman7** [comment]
My brain hurts after doing that
